### PR TITLE
Better inform users of permissions errors by tmutil Error (-50), fixes #14

### LINKED ISSUE #14: Bug:" Error (-50) while attempting to change exclusion setting " while running heptapod run
Running command

`heptpod run`

leads to following error:
`
Error (-50) while attempting to change exclusion setting.
`

image

Is it a problem with heptapod or with my machine?

Hint: I cannot print the logfile as it contains sensitive data from my employeers projects. The log file lists a lot of directories to exclude, but no further error.

### PR DESCRIPTION
**Pull request by sfleiter**

### CODE REVIEW

File: pkg/tmutil/tmutil.go [hunk 1]
```diff
@@ -101,6 +102,19 @@ func checkPath(path string, verbose int) (bool, error) {
 	return !strings.Contains(s, "[Excluded]"), nil
 }
 
+func printTmutilError(path string, out bytes.Buffer, outErr bytes.Buffer) {
```
Comment (sfleiter) [inline pkg/tmutil/tmutil.go:105]: I manually verified write permissions are the one needed for files and directories for adding or removing exclusions, they are not needed for checking

**Comment by tg44** [comment]
`undefined: strings.CutPrefix` do you want to upgrade things from go 1.17 to some newer version too?

**Comment by sfleiter** [comment]
> `undefined: strings.CutPrefix` do you want to upgrade things from go 1.17 to some newer version too?

See https://github.com/tg44/heptapod/pull/21
